version: 2
updates:
- package-ecosystem: cargo
  directory: "/services/cli"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/services/backend"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
