steps:
    - id: "Build backend"
      name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/uvindex-backend:$SHORT_SHA", "./services/backend"]

    - id: "Build cli"
      name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/uvindex-cli:$SHORT_SHA", "./services/cli"]
      waitFor: ['-']

    - id: "Push built backend image to registry"
      name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/uvindex-backend"]
      waitFor: ["Build backend"]

    - name: 'gcr.io/cloud-builders/kubectl'
      id: 'Deploy backend image to kubernetes'
      entrypoint: 'bash'
      args:
          - '-c'
          - |
            [[ "$BRANCH_NAME" == "master" ]] && /builder/kubectl.bash set image deployment/uvindex-backend uvindex-backend=gcr.io/$PROJECT_ID/uvindex-backend:$SHORT_SHA || echo "skipping k80s deployment"
      substitutions:
        _CLOUDSDK_COMPUTE_ZONE: # no default value
        _CLOUDSDK_CONTAINER_CLUSTER: # no default value

timeout: 1800s
