steps:
  # Cloud build has issue with multi-stage build. Workaround as per https://stackoverflow.com/a/58791983/7056420
  # BlockedTODO: https://github.com/moby/moby/issues/39120
  # BlockedTODO: https://github.com/moby/buildkit/issues/1972
  # Remove these two steps once this issue is resolved
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'docker/dockerfile:experimental']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'docker/dockerfile:1.0-experimental']

  - id: "Build backend"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "--progress=plain", "-t", "gcr.io/$PROJECT_ID/$_BACKEND_SERVICE_NAME:$SHORT_SHA", "./services/backend"]
    env:
      - 'DOCKER_BUILDKIT=1'

  - id: "Build cli"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "--progress=plain", "-t", "gcr.io/$PROJECT_ID/$_CLI_SERVICE_NAME:$SHORT_SHA", "./services/cli"]
    env:
      - 'DOCKER_BUILDKIT=1'
    waitFor: ["-"]

  - id: "Push built backend image to registry"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$_BACKEND_SERVICE_NAME"]
    waitFor: ["Build backend"]

  - id: "Promote backend image to latest"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - '-c'
      - |
        [[ "$BRANCH_NAME" == "master" ]] && gcloud container images add-tag gcr.io/$PROJECT_ID/$_BACKEND_SERVICE_NAME:$SHORT_SHA gcr.io/$PROJECT_ID/$_BACKEND_SERVICE_NAME:latest || echo "skipping..."

  - id: "Deploy backend image to cloud run"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - '-c'
      - |
        [[ "$BRANCH_NAME" == "master" ]] && gcloud run deploy $_CLOUD_RUN_SERVICE_NAME --image gcr.io/$PROJECT_ID/$_BACKEND_SERVICE_NAME:$SHORT_SHA --region $_CLOUD_RUN_REGION --platform managed --allow-unauthenticated || echo "skipping..."

substitutions:
    _CLOUD_RUN_SERVICE_NAME: "" # default value
    _CLOUD_RUN_REGION: "" # default value
    _BACKEND_SERVICE_NAME: "" # default value
    _CLI_SERVICE_NAME: "" # default value
timeout: 2700s
