version: '3.7'

services:
  uvindex:
    image: uvindex
    build:
      context: .
      target: dev
    environment:
      - WEATHERBIT_API_KEY
      - OPENWEATHER_API_KEY
    stdin_open: true
    tty: true
    volumes:
      - .:/uvindex
