version: '3.7'

services:
  backend:
    image: backend
    build:
      context: ./backend
      target: dev
    environment:
      - WEATHERBIT_API_KEY
      - OPENWEATHER_API_KEY
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/backend
