version: '3.7'

services:
  backend:
    image: backend
    build:
      context: ./backend
      target: dev
    environment:
      - WEATHERBIT_API_KEY
      - OPENWEATHER_API_KEY
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/backend

  cli:
    image: cli
    build:
      context: ./cli
      target: dev
    environment:
      - UVINDEX_BACKEND_PROTOCOL=http
      - UVINDEX_BACKEND_HOST=backend
      - UVINDEX_BACKEND_PORT=8000
    stdin_open: true
    tty: true
    volumes:
      - ./cli:/cli
